version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    networks:
      - lms-network
    restart: always
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5200:5200"
    volumes:
      - ./server:/app
    depends_on:
      - client  
    environment:
      - PORT=5200
      - MONGODB_URI=mongodb+srv://employee:Gauravghuge7@employee.c7zn40c.mongodb.net/employee
      - JWT_SECRET=secret
      - CLIENT_URL=http://localhost
      - CLOUDINARY_CLOUD_NAME=dsh5742fk
      - CLOUDINARY_API_KEY=899594559273632
      - CLOUDINARY_API_SECRET=9E2v2LfZFqO2qiFf1-yuZmO3JX8
    networks:
      - lms-network

networks:
  ems-network:
    driver: bridge
