version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"

    volumes:
      - ./client:/app
    
    networks:
      - ems-network
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5200:5200"
    volumes:
      - ./server:/app
    depends_on:
      - client  
    networks:
      - ems-network
    env_file:
      - .env


networks:
  ems-network:
    driver: bridge
